# Setup
title:               Cen10 Writers
tagline:             'Creative Writing @CHS'
description:         'Poems for Patriots'
url:                 'https://cen10writers.github.io/'
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              KR
  url:               http://kalkr.online
  email:             me@kalkr.online

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-cayman
