# Setup
title:               Poems Blog (tm)
tagline:             'CHS Web Whatever'
description:         'Poems for Centennial'
url:                 'https://kalkronline.github.io'
baseurl:             '/posts'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kale Riley
  url:               http://kalkr.online
  email:             me@kalkr.online

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y
